export const SECTION_ONE = [
  `The Director of Security was seven minutes into her prepared remarks when she began her repeated misgendering of an engineering teammate who had transitioned three years before they had ever met each other. Marc knew she had sharpened that knife. Everyone in the room knew it. No one said a word. She was close with a chief, and closeness with a chief was a currency that outranked human decency, productivity, and the forty-page values document that HR had distributed at the last all-hands. A document that espoused the culture and lived in a Slack channel with nine hundred and eighty members that hadn't seen a message since last October. Because, unironically, the head of HR had deemed any human who was not the head of HR unfit to post in the human resources Slack channel.`,

  `Marc\u2019s mind started to wander as the Director continued. The company had launched a cryptocurrency token the month before. It stuck in Marc\u2019s mind. A CRM platform that helped enterprises manage sales pipelines, customer data, and revenue operations had decided it needed a utility token. The CEO had watched a sitting president of the United States shill a memecoin from the Oval Office and decided that was permission. A rewards token. Earn it by closing deals. Spend it on premium analytics. Six weeks to ship. The compliance team got a slide deck. The slide deck said "regulatory alignment in progress." Nobody had called the lawyers. A CRM company was minting coins while its own engineers were filing expense reports through a system that crashed every other Friday.`,

  `The PM had opened the sync with his usual bingo card. OKRs. KPIs. SLAs. A P0 that had been a P0 for six weeks and would remain a P0 for six more because naming a thing is not the same as fixing it. Eyes glossed before his first run-on sentence ended. Half the C-suite was on the call. Not the half that made decisions. The half that enjoyed watching the levels beneath them nod.`,

  `Marc Aldrin sat in the 3rd seat from the presenter at the head of the conference room. The tiled Zoom display of muted video feeds on the projector made every attendee look like a Lego person\u2014unrecognizable, silent\u2014attending because you had to or you would be viewed as unengaged. Engaged in what though? There was 3.8M worth of salary listening to what could have been an email with three bullet points. Marc\u2019s coffee was going cold. The mug was from GOTO Chicago in 2017, back when he still wrote code. He kept it the way someone keeps a photograph of a place they used to live.`,

  `He ran five engineering managers. Each of them ran five to ten engineers. Pipeline automation. Contact graph ingestion. Third-party integrations with every payments provider, marketing platform, and ERP that their enterprise clients demanded. Data residency compliance across forty countries with forty different privacy regimes, plus SOC 2 audits that nobody enjoyed and everybody needed. His teams\u2019 systems handled billions of messages daily and hadn\u2019t gone down in twenty-four months.`,

  `His boss spoke next. The Director of Engineering. Marc watched him the way you watch a weatherman describe sunshine during a flood. The DoE agreed the team had to do better. He did not say at what. He never did. Specificity would have required him to know what the teams were building, and knowing what the teams were building would have required him to attend a meeting that wasn\u2019t this one. He had a chief of staff who converted his abstractions into Jira epics. He had a calendar blocked with syncs he attended on mute. He requested headcount and asked the occasional question, always in front of the CTO, that proved he had read the executive summary of a document his chief of staff had summarized from a document an engineer had written.`,

  `He was a director of nothing. He directed nothing. He was a human API. His one goal was to abstract away the complexity, the complaints, the needs, the lack of resourcing, the frustrated end users, and button everything up into a tight, uniform envelope that sold the wins and ignored the glaring failures.`,

  `He mentioned a retrospective. Next Wednesday. A meeting in the future to discuss a meeting about a past failure. Leadership had read a snippet on X about better outcomes from documenting failures. Nobody mentioned that no one had read the last four postmortems. Nobody mentioned that the systemic issues those postmortems identified had never received a single resource for remediation. There was no time. There was a backlog of thirty-six months of feature work that the roadmap committee had approved, that the quarterly planning process had blessed, and that the organization would spend the next six weeks re-planning before declaring the plan obsolete by week two of execution.`,

  `The retrospective was not a solution. It was exhaust from a machine built so heavy with its tiers and so segmented by its self-imposed verticals that the weight of itself prevented any real value creation. But the failures would be documented for the next grand rearchitecture of the org chart coming in twenty-four months.`,

  `Marc knew all of this. He had known it for months. He had stood at whiteboards and written action items and assigned owners and watched the board go stale inside a week because the people who owned the actions were already drowning in the work they\u2019d been assigned before the retrospective created more work about the work. He had done this a dozen times. He was good at it. He was good at every version of the job he had ever held.`,

  `He was starting to suspect that being good at this version of the job was the problem.`,
];

export const SECTION_TWO = [
  `This book is an indictment.`,

  `Not of the people in that room. Not of Marc, who is a composite drawn from my fifteen years in software engineering and the engineering organizations I and friends have worked inside. Not of the PM with his acronyms. Not of the DoE with his muted syncs. Not even of the Director of Security with her sharpened knife. They are operating rationally inside a system that rewards proximity to power over the ability to create value.`,

  `The indictment is of the system.`,

  `The modern engineering organization is a government contract wearing a hoodie. The people who control the resources are evaluated by how many resources they control. Directors are promoted for growing teams. Not for shrinking them. VPs are celebrated for landing headcount. Not for delivering the same output with fewer people. The career ladder exists to create a legibility structure that lets the organization justify its own complexity to itself. Every rung is a fiefdom. Every promotion is a territorial expansion. Every calibration meeting is a political negotiation. Conducted on behalf of engineers who are not in the room. By managers whose own advancement depends on the outcome.`,

  `This is not one company. This is the industry. I have spent fifteen years inside engineering organizations and beside them. As an engineer. As a manager of managers. As a founder. As someone whose network spans trading firms, fintechs, exchanges, startups, and enterprises across three continents. Friends who lead platform teams at public companies. Former colleagues who left to start their own shops. Founders who call me when their org chart stops making sense. The pattern repeats in every conversation. The names change. The org chart doesn\u2019t.`,

  `Architecture review boards staffed by people who haven\u2019t touched production code in years. Making decisions about systems they couldn\u2019t operate if the on-call didn\u2019t show up. Calibration meetings where a person\u2019s career trajectory is negotiated by people who have never read their code. Platform initiatives with eighteen-month timelines and forty-person teams and success criteria so vague that failure is definitionally impossible because nobody defined success precisely enough to be falsified. Millions in fully loaded headcount. Less value delivered than one engineer with a clear problem, a user to talk to, and a week.`,

  `Fiefdoms built on proximity, on shared hobbies, kids at the same school, houses in the same neighborhood, that survive three reorgs because closeness outranks competence. Leaders who measure their own success by the size of the empire beneath them. Budgets defended not because the work requires the money but because the person defending the budget is evaluated by the size of it. Castles in the sky, built with other people\u2019s time, justified by slides nobody challenges because challenging the slide means challenging the VP who commissioned it.`,

  `I have seen all of this. I have participated in some of it. I have watched friends and colleagues live through the rest. The stories in this book are composites. Drawn from my own experience, from late-night conversations with directors who couldn\u2019t say these things inside their own companies, from founders who left because they couldn\u2019t unsee it, from engineers at every level who described the same dysfunction in different buildings with different logos on the wall.`,

  `I have been good at the game and I have failed sensationally at the honesty. I have taken risks when the truth was required for business success and been penalized by organizations that preferred the comfortable lie. I have built ladders. I have run calibrations. I have defended headcount I suspected was overhead because the system rewarded the defense and punished the question.`,

  `I have been complicit.`,

  `But here is what the system does not understand about the people it is trying to retain: anyone under thirty in a software engineering organization has recognized the absurdity of all of this on day one. They are not unique in seeing it. Everyone sees it. The director who has been in the industry for twenty years sees it. The VP who chairs the calibration meetings sees it. But most of them are far enough along in their careers to accept the dysfunction as the permanent cost of doing business. They have mortgages. They have equity vesting schedules. They have learned to call compliance what is actually complacency, and they will ride the structure to retirement if the structure lets them.`,

  `The next generation will not. They saw the game on their first day. The calibration theater. The fiefdoms built on who golfs with whom. The retrospectives about retrospectives. The promotion packets that reward self-advocacy over engineering judgment. They are not disillusioned. They were never illusioned. They see it clearly, they play it as long as it pays, and they will leave the moment it doesn\u2019t. They are not loyal to the org chart. They are loyal to the work. And they are honest about the difference in a way that terrifies the people whose careers depend on nobody saying it out loud.`,

  `The reckoning is not coming from a book. It is coming from a generation of engineers who wield honesty the way the old guard wielded politics. They do not care about your leveling rubric. They care about whether the thing they built works and whether someone uses it. The compression is giving them somewhere to go. The startups that ship with five people. The solo founders with AI tooling and taste. The small teams that don\u2019t need a manager because the work is visible and the mission is clear. They are leaving. Quietly. Steadily. And the organizations they leave behind are discovering that the middle was not load-bearing after all.`,

  `This book is my reckoning. And the organization\u2019s.`,
];

export const SECTION_THREE = [
  `Generative AI is a forcing function, but it alone is not responsible for the coming carnage in engineering organizational charts. The next generation leads from a place of honesty. They speak truth to power. There is no place for layers of leadership without value. It isn\u2019t AI that\u2019s forcing the compression, though it is a tool of the coming compression into value-first leadership. The pressure is coming from both directions. From the technology that makes the layers unnecessary. And from the people who refuse to pretend they ever were.`,

  `I studied finance in college. Dropped out. I had watched older friends graduate with the same degree, land the jobs they were supposed to want, and loathe every hour of them while earning less than I was making in sales. There was no reason to pay tuition to earn less, I reasoned. So I sold. Inbound, outbound, the kind of selling where you learn one thing fast: you either created value for the person across the table or you wasted their time. There was no third option. A decade of that will calibrate you.`,

  `In 2010, I enrolled in community college and started studying computer science while working during the day. Not because software engineering was the fashionable path. The startup boom was still gathering. Most of the people I knew thought I was making a lateral move at best. I pivoted because software was the highest-leverage tool I had ever encountered for creating real value. Not theoretical value. Not roadmap value. Not \u201cwe grew the team by forty percent this year\u201d value. The kind of value where a user has a problem on Monday and doesn\u2019t have it on Friday because you built the thing that solved it.`,

  `Two semesters in, I was hooked. A friend from the same community college program and I pitched TechStars on a software service that would create a semantic layer across websites. Metadata that let information find you instead of you searching for it. Push instead of pull. They loved the idea. It was too early. Too costly. No obvious path to a broad user base. In hindsight, they were right. But the instinct was already locked in: find the problem, build the thing, put it in front of someone, and watch what happens.`,

  `That instinct never left. I fed it deliberately. The organizations I chose to work inside were never chosen for stability or prestige. They were chosen for freedom. Grand pivots. New platforms built from nothing. Problems where the answer wasn\u2019t incremental feature work but something that changed the shape of the business. I was lucky enough to find those environments, and I was deliberate about seeking them out. The teams I built and managed did not operate at the level of granular, sprint-sized change. They worked on grand ideas. They thrived on the optimism and the pressure of building something that communicated its own value. Not through a promotion packet. Through what it did and how it worked.`,

  `That origin left me with a lens most engineering leaders don\u2019t carry. I see every role, every process, every layer of the org chart through the question I learned in sales: did this create value, or is this overhead that has learned to justify itself?`,

  `It is not a popular question inside most engineering organizations. They prefer to answer it with proxies. Headcount growth. Roadmap completion percentage. Story points. Velocity. Number of PRs merged. Lines of code. These are not measures of value. They are measures of activity. The organizational structure exists in large part to convert activity into the appearance of value, because the appearance of value is what gets funded, and what gets funded is what survives, and what survives is what the people inside the structure have built their careers on.`,

  `I built my career on it too. I have worked on both sides of the coin: tiny startups with zero funding, internal startups spun off inside larger organizations, and global banks and proprietary trading firms where billions of events moved daily. I have scaled engineering organizations across continents and shipped products from nothing with teams small enough to fit in a single room. I sat in the calibration meetings and defended the headcount. I maintained single-digit attrition in industries that actively poach. I mentored engineers to senior, staff, and lead roles. By every conventional measure, I was a successful engineering leader. And I was. Inside the system. The system is what\u2019s breaking.`,

  `Then I left and built four products from zero. Smallest teams I could assemble. Agentic AI harnesses, LLM-driven development workflows, no layers, no coordination overhead, no career ladders, no calibrations, no meetings about meetings about meetings. And I shipped faster, at higher quality, and learned more in nine months than in any comparable period of my career.`,

  `That is not an anecdote. That is a data point in a pattern that is repeating across the industry right now, in every startup that ships with five people what used to require thirty, in every enterprise that quietly stops backfilling roles and discovers that output doesn\u2019t change, in every director who looks at their org chart and feels the ground shift.`,
];

export const SECTION_FOUR = [
  `The compression is here. It is not a prediction. It is not a thought experiment. It is a structural transformation in how engineering work is organized, and it is happening at the micro scale. The team that ships fine with six instead of eight. The manager role that disappears through attrition and nobody notices. The macro scale pretends nothing has changed. The org chart hasn\u2019t moved. It should have.`,

  `The irony would be funny if people\u2019s careers weren\u2019t at stake. We built elastic infrastructure. We built auto-scaling compute. We built databases that expand and contract with demand. We built entire cloud platforms on the principle that fixed capacity is waste and resources should flex with the work. Then we staffed the organizations that build those platforms with fixed hierarchies, fixed headcounts, fixed role definitions, and a career ladder so rigid that the only direction is up, the only pace is slow, and the only measure of progress is a title that maps to a comp band that maps to a calibration meeting that maps to a negotiation the engineer will never see.`,

  `We made the machines elastic and the humans brittle. We scaled everything except ourselves.`,

  `Why? Because politicians don\u2019t vote to abolish politicians. The director doesn\u2019t redesign the org to need fewer directors. The VP doesn\u2019t build a system that makes VPs unnecessary. The career ladder persists not because it develops people but because it is the mechanism through which the organization sees itself, and the people who run the organization are the people the ladder elevated. The structure is self-preserving. It will not reform itself. It will be compressed from outside, by economics, by AI, by the startups that prove the structure was never necessary. Or it will not be reformed at all.`,

  `This book argues for the compression. Not as a cost-cutting exercise. Not as downsizing. As resizing. The organizational equivalent of the elastic infrastructure we already know how to build. An engineering org that composes and decomposes around problems. That measures contribution through systems instead of through the interpretive labor of managers watching managers watching engineers. Deployment frequency. SLO adherence. Error budgets. User adoption. The work speaks for itself when you build the systems to listen.`,

  `That replaces the career ladder with visible, system-measured impact.`,

  `That replaces the team hierarchy with fire teams of two pairs. Expert Scalers and Slop Cannons. Deep-system thinkers and high-velocity builders. Operating within streams of subject-matter expertise: security, networking, user experience, payment rails, machine learning. Not teams with managers. Currents with practitioners.`,

  `Think of each pair as a container. Two processes inside: one Slop Cannon, one Expert Scaler. The container is elastic. It might be deployed to finance one week and sales the next. It might be composed with other containers to solve a large, high-value problem. It might be distributed for discovery across every vertical inside the organization. It might be handed an MVP for a new product and given a week. The latent capacity of these pairs is never wasted because the pairs are never permanently assigned. They flow to wherever the highest-value problem is right now. Loosely coupled. High impact. Stateless in their organizational attachment. Deeply stateful in their expertise.`,

  `The need for synchronization between these independent containers is small and specific. A lean leadership team with the capability and capacity, leveraging generative AI, to keep a finger on the pulse of diverse projects and proposals across boundaries. Not managers of the pairs. Orchestrators. Routing work, resolving conflicts, making resource decisions in real time. The engineering leadership above these containerized pairs becomes a conduit for decision-making directly with senior leadership. No translation layers. No middle management. No chief of staff summarizing a summary. The person who understands the work talks to the person who funds the work. Everything between them is overhead.`,

  `And it replaces the interview gauntlet that measures how fast you can implement a red-black tree in Rust with something that actually predicts whether a person can build. The days of ceremonial, esoteric knowledge are ending. The cost of knowledge is approaching zero. What cannot be automated is the ability to look at a system and know what doesn\u2019t need to be built at all. Systems design over vertical trivia. Latticed skill over narrow expertise. Creative, high-value problem solving over the rote reproduction of patterns that an LLM can generate in seconds. The person you want on your fire team, you will know them not by how quickly they implement code but by how quickly they identify the code that doesn\u2019t need to be written.`,

  `This is the age of the generalist who goes deep on purpose. The engineer who carries a lattice of skills across domains and applies them with taste. The builder who understands the technology landscape at an intuitive level because they have operated in enough of it to see the shape, not because they memorized the textbook for one corner of it.`,

  `And this book argues, loudly, specifically, without hedge, that the compression is the largest opportunity in a generation. For the new graduate with drive and taste and subject-matter curiosity who has been told to wait their turn on a ladder that is already collapsing under its own weight. For the mid-career engineer who has been passed over for promotion because they ship product instead of writing promotion packets.`,

  `For the neurodivergent thinker. The deep-system architect. The high-velocity builder. Who has been told they need to work on their communication when the truth is that the organization needs to work on its ability to recognize what they are communicating.`,

  `When I first got into software engineering, there was a term for the rare person who composed both sides of this coin. The neurodivergent thinker who was a deep-system architect and a high-velocity builder. You would come to them with an idea on a Friday, and by Monday morning they would have an MVP. Not a mockup. Not a wireframe. An end-to-end working prototype. They were called 10x engineers. They were unicorns. The industry treated them as anomalies. Unreplicable. Impossible to hire for. But what they actually were was a preview. They earned their place at the top of every hierarchy they entered by delivering exactly what the future engineering organization must deliver: creative, high-value output at a velocity the old structure could not process. The Expert Scaler and the Slop Cannon are the 10x engineer split into two complementary halves. The fire team is the structure that composes that output without waiting for a unicorn to walk through the door.`,

  `For every person in every engineering organization who has sat in a meeting like the one that opened this preface and thought: there has to be something better than this.`,

  `There is. It is smaller, faster, more honest, and it is being built right now by people who got tired of waiting for the system to fix itself.`,

  `Every chapter in this book is two acts. The first is a story. Characters in rooms, under pressure, navigating the compression in real time. The second is a treatise. The structural argument, stated plainly, defended with numbers, unhedged. The characters are inspired by real life. We protect the innocent and the guilty.`,

  `Let\u2019s move.`,
];
